//
// Created by russell on 20.09.16.
//

#ifndef SECONDTASKRECEIVER_MESSAGEADDDASHES_H
#define SECONDTASKRECEIVER_MESSAGEADDDASHES_H

#define MAX_SLEEP_TIME 5

void *MessageAddDashes(void *thrStr);

#endif //SECONDTASKRECEIVER_MESSAGEADDDASHES_H
