//
// Created by russell on 20.09.16.
//

#ifndef SECONDTASKRECEIVER_MESSAGEREVERSE_H
#define SECONDTASKRECEIVER_MESSAGEREVERSE_H

#define MAX_SLEEP_TIME 5

void *MessageReverse(void *thrStr);

#endif //SECONDTASKRECEIVER_MESSAGEREVERSE_H
